version: '3'
services:
    mariadb:
        image: mariadb/server:10.4
        network_mode: 'host'
        environment:
            - MARIADB_RANDOM_ROOT_PASSWORD=true
            - MARIADB_DATABASE=hivemetastore
            - MARIADB_USER=hive
            - MARIADB_PASSWORD=secret
        volumes:
            - './mariadb:/var/lib/mysql'
    hadoop-namenode:
        build: ./hadoop
        network_mode: 'host'
        entrypoint: ./start-namenode.sh
        volumes:
            - './hadoop/dfs:/mnt/data/dfs'
    hadoop-datanode:
        build: ./hadoop
        network_mode: 'host'
        entrypoint: /opt/hadoop/bin/hdfs datanode
        volumes:
            - './hadoop/dfs:/mnt/data/dfs'
    hive-metastore:
        build: ./hadoop
        network_mode: 'host'
    hive-server:
        build: ./hadoop
        network_mode: 'host'
        entrypoint: /opt/hive/bin/hive --service hiveserver2
    presto:
        build: ./presto
        network_mode: 'host'
    nifi:
        build: ./nifi
        network_mode: 'host'
        environment:
            - NIFI_WEB_HTTP_PORT=9090
        volumes:
            - './nifi/conf:/opt/nifi/nifi-current/conf'
            - './nifi/content_repository:/opt/nifi/nifi-current/content_repository'
            - './nifi/database_repository:/opt/nifi/nifi-current/database_repository'
            - './nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository'
            - './nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository'
